quiz-controllers:
    resource:
        path: ../src/Quiz/Transport/Controller/
        namespace: App\Quiz\Transport\Controller
    type: attribute
    prefix: /api
    defaults:
        _format: json
